import os
import html
from datetime import datetime


def generate_html_report(results, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    fname = f"themeguard_report_{timestamp}.html"
    fpath = os.path.join(output_dir, fname)

    findings = results.get("findings", [])
    counts = results.get("severity_counts", {})
    severity_colors = {
        "critical": "#ff4444",
        "high": "#ff8800",
        "medium": "#ffcc00",
        "low": "#44aaff",
    }

    rows = ""
    for f in findings:
        sev = f.get("severity", "low")
        color = severity_colors.get(sev, "#44aaff")
        match_html = ""
        if f.get("match"):
            match_html = f'<pre class="match">{html.escape(f["match"][:200])}</pre>'
        ctx_html = ""
        if f.get("context"):
            ctx_html = f'<pre class="context">{html.escape(f["context"])}</pre>'
        rows += f"""
        <tr>
            <td><span class="badge" style="background:{color}">{sev.upper()}</span></td>
            <td>{html.escape(f.get('file', ''))}</td>
            <td>{f.get('line', '-')}</td>
            <td>
                <strong>{html.escape(f.get('message', ''))}</strong>
                {match_html}
                {ctx_html}
            </td>
            <td><code>{html.escape(f.get('type', ''))}</code></td>
        </tr>"""

    empty_row = '<tr><td colspan="5" style="text-align:center;color:#3fb950;padding:2rem">No threats detected. Target appears clean.</td></tr>'

    report = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ThemeGuard Scan Report</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: #0d1117; color: #c9d1d9; font-family: -apple-system, 'Segoe UI', monospace; padding: 2rem; }}
  h1 {{ color: #58a6ff; margin-bottom: 0.5rem; }}
  .meta {{ color: #8b949e; margin-bottom: 2rem; font-size: 0.9rem; }}
  .stats {{ display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }}
  .stat-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem 1.5rem; min-width: 150px; }}
  .stat-card .number {{ font-size: 2rem; font-weight: bold; }}
  .stat-card .label {{ color: #8b949e; font-size: 0.85rem; }}
  table {{ width: 100%; border-collapse: collapse; background: #161b22; border-radius: 8px; overflow: hidden; }}
  th {{ background: #21262d; padding: 0.75rem 1rem; text-align: left; color: #8b949e; font-size: 0.85rem; text-transform: uppercase; }}
  td {{ padding: 0.75rem 1rem; border-top: 1px solid #21262d; vertical-align: top; }}
  tr:hover {{ background: #1c2128; }}
  .badge {{ padding: 2px 8px; border-radius: 12px; font-size: 0.75rem; font-weight: bold; color: #fff; }}
  pre {{ background: #0d1117; padding: 0.5rem; border-radius: 4px; font-size: 0.8rem; margin-top: 0.5rem; overflow-x: auto; white-space: pre-wrap; word-break: break-all; }}
  pre.match {{ border-left: 3px solid #ff4444; }}
  pre.context {{ border-left: 3px solid #30363d; color: #8b949e; }}
  code {{ background: #21262d; padding: 2px 6px; border-radius: 4px; font-size: 0.8rem; }}
  .footer {{ margin-top: 2rem; color: #484f58; font-size: 0.8rem; text-align: center; }}
</style>
</head>
<body>
<h1>ThemeGuard Scan Report</h1>
<div class="meta">
  Target: <code>{html.escape(results.get('target', ''))}</code><br>
  Scanned: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}<br>
  Files: {results.get('files_scanned', 0)} | Time: {results.get('scan_time', 0)}s |
  Signatures: {results.get('signatures', {}).get('total_signatures', 0)}
</div>

<div class="stats">
  <div class="stat-card">
    <div class="number" style="color:#ff4444">{counts.get('critical', 0)}</div>
    <div class="label">Critical</div>
  </div>
  <div class="stat-card">
    <div class="number" style="color:#ff8800">{counts.get('high', 0)}</div>
    <div class="label">High</div>
  </div>
  <div class="stat-card">
    <div class="number" style="color:#ffcc00">{counts.get('medium', 0)}</div>
    <div class="label">Medium</div>
  </div>
  <div class="stat-card">
    <div class="number" style="color:#44aaff">{counts.get('low', 0)}</div>
    <div class="label">Low</div>
  </div>
  <div class="stat-card">
    <div class="number" style="color:#58a6ff">{results.get('total_findings', 0)}</div>
    <div class="label">Total</div>
  </div>
</div>

<table>
<thead>
<tr><th>Severity</th><th>File</th><th>Line</th><th>Details</th><th>Type</th></tr>
</thead>
<tbody>
{rows if rows else empty_row}
</tbody>
</table>
<div class="footer">Generated by ThemeGuard v1.0.0 | by Muhammad Abid (@V3n0mSh3ll)</div>
</body>
</html>"""

    with open(fpath, "w", encoding="utf-8") as fh:
        fh.write(report)
    return fpath
